# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_auto_20180223_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('review', models.TextField(default='', max_length=1000)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
