# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='itemname',
        ),
    ]
